export const buglesData = [
  {
    id: '0',
    name: 'Sentido',
    duration: 7000,
    artist: 'José',
    uriAudio: '',
    uriImg: '',
  },
  {
    id: '1',
    name: 'Descansar',
    duration: 8000,
    artist: 'José',
    uriAudio: '',
    uriImg: '',
  },
  {
    id: '2',
    name: 'Ordinário Marche',
    duration: 10000,
    artist: 'José',
    uriAudio: '',
    uriImg: '',
  },
  {
    id: '3',
    name: 'Alto',
    duration: 6000,
    artist: 'José',
    uriAudio: '',
    uriImg: '',
  },
  {
    id: '4',
    name: 'Apresentar Arma',
    duration: 8000,
    artist: 'José',
    uriAudio: '',
    uriImg: '',
  },
]
