import { AudioType } from '../../../@types/audioTypes'

export const buglesData = [
  {
    id: 'b_1',
    name: 'Alto',
    duration: 5590,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_2',
    name: 'Apresentar arma',
    duration: 9000,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_3',
    name: 'Avançar',
    duration: 5830,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_4',
    name: 'À vontade',
    duration: 5090,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_5',
    name: 'Bandeira Avançar',
    duration: 17180,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_6',
    name: 'Batalhão Grupo',
    duration: 4080,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_7',
    name: 'CBMDF',
    duration: 4680,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_8',
    name: 'Cobrir',
    duration: 4900,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_9',
    name: 'Comandante ABMIL',
    duration: 26690,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_10',
    name: 'Comandante CBMDF',
    duration: 14280,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_11',
    name: 'Comandante de Área ou Operacional CBMDF',
    duration: 19920,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_12',
    name: 'Comandante PMDF',
    duration: 15050,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_13',
    name: 'Descansar',
    duration: 5710,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_14',
    name: 'Descansar Arma',
    duration: 4540,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_15',
    name: 'Direita',
    duration: 9550,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_16',
    name: 'Diretor de Ensino CBMDF',
    duration: 21310,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_17',
    name: 'Em continência',
    duration: 24430,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_18',
    name: 'Em continência à Bandeira',
    duration: 5380,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_19',
    name: 'Esquerda',
    duration: 10100,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_20',
    name: 'Firme',
    duration: 5060,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_21',
    name: 'Fora de forma',
    duration: 7300,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_22',
    name: 'Granadeira',
    duration: 18650,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_23',
    name: 'Início do Expediente',
    duration: 13560,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_24',
    name: 'Marcar Passo',
    duration: 7510,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_25',
    name: 'Marcha Batida',
    duration: 33550,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_26',
    name: 'Meia Volta Volver',
    duration: 10780,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_27',
    name: 'Ministros de Estado ou Governadores',
    duration: 7200,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_28',
    name: 'Olhar à Direita',
    duration: 10080,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_29',
    name: 'Olhar Frente',
    duration: 6650,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_30',
    name: 'Ombro Arma',
    duration: 6740,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_31',
    name: 'Ordinário Marche',
    duration: 10580,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_32',
    name: 'Presidente da República',
    duration: 9550,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_33',
    name: 'Reunir',
    duration: 7300,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_34',
    name: 'Sentido',
    duration: 8020,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_35',
    name: 'STF Senado ou Câmara dos Deputados',
    duration: 8690,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_36',
    name: 'Sub Comandante CBMDF',
    duration: 17140,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_37',
    name: 'Sub Comandante PMDF',
    duration: 17590,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_38',
    name: 'Término do Expediente',
    duration: 17860,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_39',
    name: 'Última forma',
    duration: 6050,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_40',
    name: 'Vice Presidente da República',
    duration: 8760,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
]
