import { AudioType } from '../../../@types/audioTypes'

export const buglesData = [
  {
    id: 'b_1',
    name: 'A Granadeira - 11 Primeiros Compassos',
    duration: 11830,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_2',
    name: 'A Granadeira - 13 Primeiros Compassos',
    duration: 13820,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_3',
    name: 'A Granadeira Completa',
    duration: 18050,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_4',
    name: 'Alto',
    duration: 5300,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_5',
    name: 'Apresentar Arma',
    duration: 7550,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_6',
    name: 'Avançar',
    duration: 5930,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_7',
    name: 'Bandeira Nacional',
    duration: 11550,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_8',
    name: 'Batalhão Grupo',
    duration: 3030,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_9',
    name: 'Chefe Do DEPCT do CBMDF',
    duration: 17160,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_10',
    name: 'Cobrir',
    duration: 6970,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_11',
    name: 'Comandante da ABMIL',
    duration: 25990,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_12',
    name: 'Comandante de Área do CBMDF',
    duration: 19070,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_13',
    name: 'Comandante-Geral da PMDF',
    duration: 14450,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_14',
    name: 'Comandante-Geral do CBMDF',
    duration: 13820,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_15',
    name: 'Corpo de Bombeiros Reunir',
    duration: 10580,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_16',
    name: 'Descansar',
    duration: 4730,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_17',
    name: 'Descansar Arma',
    duration: 4830,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_18',
    name: 'Direita',
    duration: 8020,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_19',
    name: 'Diretor de Ensino do CBMDF',
    duration: 18940,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_20',
    name: 'Em Continência',
    duration: 5750,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_21',
    name: 'Esquerda',
    duration: 9200,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_22',
    name: 'Firme',
    duration: 5020,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_23',
    name: 'Fora de Forma',
    duration: 7000,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_24',
    name: 'Início do Expediente Administrativo',
    duration: 15230,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_25',
    name: 'Marcar Passo',
    duration: 7290,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_26',
    name: 'Marcha Batida 12 Últimos Compassos',
    duration: 25050,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_27',
    name: 'Marcha Batida Completa',
    duration: 33040,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_28',
    name: 'Meia Volta',
    duration: 10420,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_29',
    name: 'Ministro de Estado ou Governadores',
    duration: 6640,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_30',
    name: 'Olhar A Direita',
    duration: 10970,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_31',
    name: 'Olhar Frente',
    duration: 6320,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_32',
    name: 'Ombro Arma',
    duration: 5540,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_33',
    name: 'Ordinário Marche',
    duration: 11000,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_34',
    name: 'Ordinário Marche Com Bumbo',
    duration: 10370,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_35',
    name: 'Presidente da República',
    duration: 9350,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_36',
    name: 'Sentido',
    duration: 8050,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_37',
    name: 'STF, Senado e Câmara dos Deputados',
    duration: 8330,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_38',
    name: 'Sub Comandante-Geral da PMDF',
    duration: 19040,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_39',
    name: 'Sub Comandante-Geral do CBMDF',
    duration: 16270,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_40',
    name: 'Término do Expediente Administrativo',
    duration: 17660,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_41',
    name: 'Toque de Silêncio',
    duration: 30350,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_42',
    name: 'Última Forma',
    duration: 5960,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'b_43',
    name: 'Vice-Presidente da República',
    duration: 9530,
    artist: 'ST Fonseca',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
]
