import { AudioType } from '../../../@types/audioTypes'

export const beatsData = [
  {
    id: 'beat_1',
    name: '80',
    duration: 180000,
    artist: '',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'beat_2',
    name: '90',
    duration: 180000,
    artist: '',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'beat_3',
    name: '100',
    duration: 180000,
    artist: '',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'beat_4',
    name: '110',
    duration: 180000,
    artist: '',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'beat_5',
    name: '120',
    duration: 180000,
    artist: '',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'beat_6',
    name: '130',
    duration: 180000,
    artist: '',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
  {
    id: 'beat_7',
    name: '140',
    duration: 180000,
    artist: '',
    uriAudio: '',
    uriImg: '',
    type: AudioType.BUGLE,
  },
]
